### ISSUE TITLE
Data prediction - Graphs

### ISSUE THREAD

**Issue by Nidhi-1211** [TechLabs-Berlin/st21-beachblue#3]
Creating various visual graphs for further interpretation. Add the graphs in the report

**Comment by AronMikes** [comment]
The actual values for the test set of the Decision Tree Regressor:
![image](https://user-images.githubusercontent.com/59264146/124748257-286ccb00-df23-11eb-9a9a-f55899af538f.png)

The predicted values for the test set of the Decision Tree Regressor:
![image](https://user-images.githubusercontent.com/59264146/124748370-518d5b80-df23-11eb-81b1-ac6a32f7f845.png)

The similarities for the spots using  the TF-IDF algorithm (rejected idea):
![image](https://user-images.githubusercontent.com/59264146/124748570-931e0680-df23-11eb-88bc-76a1c71eaaa8.png)

Visualizing the computational cost for clustering by K-Modes (rejected idea):
![image](https://user-images.githubusercontent.com/59264146/124748752-c6609580-df23-11eb-80d4-9b8752a7b64e.png)

**Comment by Nidhi-1211** [comment]
![Figure_1](https://user-images.githubusercontent.com/80587078/125157430-3a40af00-e16b-11eb-9a92-fc758b0cd4a3.png)

Graphs of the training and testing data set of knn classifier model 

![Figure_2](https://user-images.githubusercontent.com/80587078/125157453-5b090480-e16b-11eb-9437-68b98f380df0.png)

Tested various knn values to see which value would give the best prediction score
